{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "p0W867ZhdkdI",
        "outputId": "b12df34c-c21e-457c-b945-e015aabf141f",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"
          ]
        }
      ],
      "source": [
        "'''\n",
        "\n",
        "資料 mapping 至google drive\n",
        "\n",
        "把資料寫在/content/drive\n",
        "\n",
        "即可保存在 google drive內\n",
        "\n",
        "'''\n",
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "id": "uB-ssmBtd5ac",
        "outputId": "e68224a5-f622-4794-d0ea-2e2e5479fea6",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n",
            "Requirement already satisfied: line-bot-sdk in /usr/local/lib/python3.9/dist-packages (2.4.2)\n",
            "Requirement already satisfied: flask in /usr/local/lib/python3.9/dist-packages (2.2.3)\n",
            "Requirement already satisfied: flask-ngrok in /usr/local/lib/python3.9/dist-packages (0.0.25)\n",
            "Requirement already satisfied: aiohttp==3.8.4 in /usr/local/lib/python3.9/dist-packages (from line-bot-sdk) (3.8.4)\n",
            "Requirement already satisfied: future in /usr/local/lib/python3.9/dist-packages (from line-bot-sdk) (0.16.0)\n",
            "Requirement already satisfied: requests==2.28.2 in /usr/local/lib/python3.9/dist-packages (from line-bot-sdk) (2.28.2)\n",
            "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.9/dist-packages (from aiohttp==3.8.4->line-bot-sdk) (4.0.2)\n",
            "Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp==3.8.4->line-bot-sdk) (3.1.0)\n",
            "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from aiohttp==3.8.4->line-bot-sdk) (1.3.3)\n",
            "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp==3.8.4->line-bot-sdk) (22.2.0)\n",
            "Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp==3.8.4->line-bot-sdk) (1.8.2)\n",
            "Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.9/dist-packages (from aiohttp==3.8.4->line-bot-sdk) (1.3.1)\n",
            "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/dist-packages (from aiohttp==3.8.4->line-bot-sdk) (6.0.4)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests==2.28.2->line-bot-sdk) (2.10)\n",
            "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests==2.28.2->line-bot-sdk) (1.26.15)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests==2.28.2->line-bot-sdk) (2022.12.7)\n",
            "Requirement already satisfied: importlib-metadata>=3.6.0 in /usr/local/lib/python3.9/dist-packages (from flask) (6.0.0)\n",
            "Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.9/dist-packages (from flask) (2.1.2)\n",
            "Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.9/dist-packages (from flask) (8.1.3)\n",
            "Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/lib/python3.9/dist-packages (from flask) (2.2.3)\n",
            "Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.9/dist-packages (from flask) (3.1.2)\n",
            "Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata>=3.6.0->flask) (3.15.0)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from Jinja2>=3.0->flask) (2.1.2)\n"
          ]
        }
      ],
      "source": [
        "'''\n",
        "\n",
        "'''\n",
        "\n",
        "!pip install line-bot-sdk flask flask-ngrok"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "id": "JS4BNBZQd7HU"
      },
      "outputs": [],
      "source": [
        "'''\n",
        "引用套件\n",
        "'''\n",
        "\n",
        "# 引用Web Server套件\n",
        "from flask import Flask, request, abort, jsonify\n",
        "\n",
        "# 載入json處理套件\n",
        "import json\n",
        "\n",
        "# 外部連結自動生成套件\n",
        "from flask_ngrok import run_with_ngrok\n",
        "\n",
        "# 從linebot 套件包裡引用 LineBotApi 與 WebhookHandler 類別\n",
        "from linebot import (\n",
        "    LineBotApi, WebhookHandler\n",
        ")\n",
        "\n",
        "# 引用無效簽章錯誤\n",
        "from linebot.exceptions import (\n",
        "    InvalidSignatureError\n",
        ")\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "id": "DQjGb3Hjiy5U"
      },
      "outputs": [],
      "source": [
        "# 設定Server啟用細節\n",
        "app = Flask(__name__,static_url_path = \"/素材\" , static_folder = \"./素材/\")\n",
        "run_with_ngrok(app)\n",
        "\n",
        "# 生成實體物件\n",
        "# 跟line 溝通用\n",
        "line_bot_api = LineBotApi(\"vtaRo4pkLqIZjk50gBJ53fFtMpg+8unl4TvLKbyvENmbWkzdriMNIeVm87ZWRBdTeDL7YM4hGte+BrNMmYscJ1WNPvCQbheXUbVevrlKB3zP3CaeRjbPQRPHMsqW+037bLOogqjOrh5ssRj53kqQMQdB04t89/1O/w1cDnyilFU=\")\n",
        "# 收發訊息用\n",
        "handler = WebhookHandler(\"de385af73d2121e65ca6fc0490991b02\")\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "id": "gUuI4lVzi5M7"
      },
      "outputs": [],
      "source": [
        "\n",
        "# 啟動server對外接口，使Line能丟消息進來\n",
        "@app.route(\"/\", methods=['POST'])\n",
        "def callback():\n",
        "    # get X-Line-Signature header value\n",
        "    signature = request.headers['X-Line-Signature']\n",
        "\n",
        "    # get request body as text\n",
        "    body = request.get_data(as_text=True)\n",
        "    app.logger.info(\"Request body: \" + body)\n",
        "\n",
        "    # handle webhook body\n",
        "    try:\n",
        "        handler.handle(body, signature)\n",
        "    except InvalidSignatureError:\n",
        "        abort(400)\n",
        "\n",
        "    return 'OK'"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 10,
      "metadata": {
        "id": "iKUrvJ74jQMz"
      },
      "outputs": [],
      "source": [
        "'''\n",
        "消息判斷器\n",
        "讀取指定的json檔案後，把json解析成不同格式的SendMessage\n",
        "讀取檔案，\n",
        "把內容轉換成json\n",
        "將json轉換成消息\n",
        "放回array中，並把array傳出。\n",
        "'''\n",
        "\n",
        "# 引用會用到的套件\n",
        "from linebot.models import (\n",
        "    ImagemapSendMessage, TextSendMessage, ImageSendMessage, LocationSendMessage,\n",
        "    FlexSendMessage, VideoSendMessage, StickerSendMessage, AudioSendMessage\n",
        ")\n",
        "\n",
        "from linebot.models.template import (\n",
        "    ButtonsTemplate,CarouselTemplate,ConfirmTemplate,ImageCarouselTemplate\n",
        "    \n",
        ")\n",
        "\n",
        "from linebot.models.template import *\n",
        "\n",
        "def detect_json_array_to_new_message_array(fileName):\n",
        "    \n",
        "    #開啟檔案，轉成json\n",
        "    with open(fileName,encoding='utf8') as f:\n",
        "        jsonArray = json.load(f)\n",
        "    \"\"\"\n",
        "    先做一個array\n",
        "    判斷消息,判斷裡面的json的type欄位\n",
        "    依據type欄位轉換成xxxSendMessage 消息物件\n",
        "    append 到先前的空白array\n",
        "    \"\"\"\n",
        "    # 解析json\n",
        "    returnArray = []\n",
        "    for jsonObject in jsonArray:\n",
        "\n",
        "        # 讀取其用來判斷的元件\n",
        "        message_type = jsonObject.get('type')\n",
        "        \n",
        "        # 轉換\n",
        "        if message_type == 'text':\n",
        "            returnArray.append(TextSendMessage.new_from_json_dict(jsonObject))\n",
        "        elif message_type == 'imagemap':\n",
        "            returnArray.append(ImagemapSendMessage.new_from_json_dict(jsonObject))\n",
        "        elif message_type == 'template':\n",
        "            returnArray.append(TemplateSendMessage.new_from_json_dict(jsonObject))\n",
        "        elif message_type == 'image':\n",
        "            returnArray.append(ImageSendMessage.new_from_json_dict(jsonObject))\n",
        "        elif message_type == 'sticker':\n",
        "            returnArray.append(StickerSendMessage.new_from_json_dict(jsonObject))  \n",
        "        elif message_type == 'audio':\n",
        "            returnArray.append(AudioSendMessage.new_from_json_dict(jsonObject))  \n",
        "        elif message_type == 'location':\n",
        "            returnArray.append(LocationSendMessage.new_from_json_dict(jsonObject))\n",
        "        elif message_type == 'flex':\n",
        "            returnArray.append(FlexSendMessage.new_from_json_dict(jsonObject))  \n",
        "        elif message_type == 'video':\n",
        "            returnArray.append(VideoSendMessage.new_from_json_dict(jsonObject))    \n",
        "\n",
        "\n",
        "    # 回傳\n",
        "    return returnArray\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 11,
      "metadata": {
        "id": "zWhCWzrfjge5"
      },
      "outputs": [],
      "source": [
        "\n",
        "# 引用套件\n",
        "from linebot.models import (\n",
        "    MessageEvent, TextMessage\n",
        ")\n",
        "\n",
        "\n",
        "# 文字消息處理\n",
        "@handler.add(MessageEvent,message=TextMessage)\n",
        "def process_text_message(event):\n",
        "\n",
        "    # 讀取本地檔案，並轉譯成消息\n",
        "    result_message_array =[]\n",
        "    # 用戶輸入文字 我就在本地方找相應的json\n",
        "    replyJsonPath = \"/content/drive/MyDrive/line_bot_content/\" + event.message.text + \".json\"\n",
        "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
        "\n",
        "    # 發送\n",
        "    line_bot_api.reply_message(\n",
        "        event.reply_token,\n",
        "        result_message_array\n",
        "    )"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "fFwaojqca8F6",
        "outputId": "67905a9c-897e-41d8-80c4-8f9c9113f7a1",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * Serving Flask app '__main__'\n",
            " * Debug mode: off\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "INFO:werkzeug:\u001b[31m\u001b[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\u001b[0m\n",
            " * Running on http://127.0.0.1:5000\n",
            "INFO:werkzeug:\u001b[33mPress CTRL+C to quit\u001b[0m\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * Running on http://3e5d-35-245-62-166.ngrok.io\n",
            " * Traffic stats available on http://127.0.0.1:4040\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 39, in detect_json_array_to_new_message_array\n",
            "    message_type = jsonObject.get('type')\n",
            "AttributeError: 'str' object has no attribute 'get'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:44:18] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 18, in process_text_message\n",
            "    line_bot_api.reply_message(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 116, in reply_message\n",
            "    self._post(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2033, in _post\n",
            "    self.__check_error(response)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2069, in __check_error\n",
            "    raise LineBotApiError(\n",
            "linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=e4c85f4c-7b24-4796-b705-b015c41332b9, error_response={\"details\": [{\"message\": \"Invalid action URI\"}], \"message\": \"A message (messages[0])\\u00a0in the request body is invalid\"}, headers={'Content-Type': 'application/json', 'Server': 'envoy', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': 'e4c85f4c-7b24-4796-b705-b015c41332b9', 'x-xss-protection': '1; mode=block', 'Content-Length': '114', 'Expires': 'Thu, 16 Mar 2023 07:44:58 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 16 Mar 2023 07:44:58 GMT', 'Connection': 'close'}\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:44:58] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 18, in process_text_message\n",
            "    line_bot_api.reply_message(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 116, in reply_message\n",
            "    self._post(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2033, in _post\n",
            "    self.__check_error(response)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2069, in __check_error\n",
            "    raise LineBotApiError(\n",
            "linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=c1e6e61c-9b32-4d66-ba41-d995e02d2c2c, error_response={\"details\": [{\"message\": \"Invalid action URI\"}], \"message\": \"A message (messages[0])\\u00a0in the request body is invalid\"}, headers={'Content-Type': 'application/json', 'Server': 'envoy', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': 'c1e6e61c-9b32-4d66-ba41-d995e02d2c2c', 'x-xss-protection': '1; mode=block', 'Content-Length': '114', 'Expires': 'Thu, 16 Mar 2023 07:45:33 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 16 Mar 2023 07:45:33 GMT', 'Connection': 'close'}\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:45:33] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:46:43] \"POST / HTTP/1.1\" 200 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 18, in process_text_message\n",
            "    line_bot_api.reply_message(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 116, in reply_message\n",
            "    self._post(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2033, in _post\n",
            "    self.__check_error(response)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2069, in __check_error\n",
            "    raise LineBotApiError(\n",
            "linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=63988364-ef22-4e18-93e9-b992ea587ff3, error_response={\"details\": [{\"message\": \"Must be a valid HTTPS URL\", \"property\": \"messages[1].originalContentUrl\"}], \"message\": \"The request body has 1 error(s)\"}, headers={'Content-Type': 'application/json', 'Server': 'envoy', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '63988364-ef22-4e18-93e9-b992ea587ff3', 'x-xss-protection': '1; mode=block', 'Content-Length': '141', 'Expires': 'Thu, 16 Mar 2023 07:47:26 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 16 Mar 2023 07:47:26 GMT', 'Connection': 'close'}\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:47:26] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 18, in process_text_message\n",
            "    line_bot_api.reply_message(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 116, in reply_message\n",
            "    self._post(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2033, in _post\n",
            "    self.__check_error(response)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2069, in __check_error\n",
            "    raise LineBotApiError(\n",
            "linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=adb646a4-7e30-449a-ab03-90d35657a2de, error_response={\"details\": [{\"message\": \"Must be a valid HTTPS URL\", \"property\": \"messages[0].originalContentUrl\"}], \"message\": \"The request body has 1 error(s)\"}, headers={'Content-Type': 'application/json', 'Server': 'envoy', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': 'adb646a4-7e30-449a-ab03-90d35657a2de', 'x-xss-protection': '1; mode=block', 'Content-Length': '141', 'Expires': 'Thu, 16 Mar 2023 07:47:43 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 16 Mar 2023 07:47:43 GMT', 'Connection': 'close'}\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:47:43] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:47:58] \"POST / HTTP/1.1\" 200 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 27, in detect_json_array_to_new_message_array\n",
            "    jsonArray = json.load(f)\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 293, in load\n",
            "    return loads(fp.read(),\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 346, in loads\n",
            "    return _default_decoder.decode(s)\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 337, in decode\n",
            "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 355, in raw_decode\n",
            "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
            "json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 332)\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:48:48] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 27, in detect_json_array_to_new_message_array\n",
            "    jsonArray = json.load(f)\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 293, in load\n",
            "    return loads(fp.read(),\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 346, in loads\n",
            "    return _default_decoder.decode(s)\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 337, in decode\n",
            "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 355, in raw_decode\n",
            "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
            "json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 332)\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:49:20] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 27, in detect_json_array_to_new_message_array\n",
            "    jsonArray = json.load(f)\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 293, in load\n",
            "    return loads(fp.read(),\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 346, in loads\n",
            "    return _default_decoder.decode(s)\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 337, in decode\n",
            "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 355, in raw_decode\n",
            "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
            "json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 332)\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:49:31] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 27, in detect_json_array_to_new_message_array\n",
            "    jsonArray = json.load(f)\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 293, in load\n",
            "    return loads(fp.read(),\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 346, in loads\n",
            "    return _default_decoder.decode(s)\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 337, in decode\n",
            "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 355, in raw_decode\n",
            "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
            "json.decoder.JSONDecodeError: Expecting value: line 4 column 25 (char 47)\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:51:05] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:51:50] \"POST / HTTP/1.1\" 200 -\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:52:25] \"POST / HTTP/1.1\" 200 -\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:53:16] \"POST / HTTP/1.1\" 200 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 26, in detect_json_array_to_new_message_array\n",
            "    with open(fileName,encoding='utf8') as f:\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/line_bot_content/我要找弱小外星人.json'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:53:30] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 27, in detect_json_array_to_new_message_array\n",
            "    jsonArray = json.load(f)\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 293, in load\n",
            "    return loads(fp.read(),\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 346, in loads\n",
            "    return _default_decoder.decode(s)\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 337, in decode\n",
            "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 353, in raw_decode\n",
            "    obj, end = self.scan_once(s, idx)\n",
            "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 67 column 1 (char 1779)\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:54:04] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 26, in detect_json_array_to_new_message_array\n",
            "    with open(fileName,encoding='utf8') as f:\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/line_bot_content/我要找弱小外星人.json'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:54:08] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 27, in detect_json_array_to_new_message_array\n",
            "    jsonArray = json.load(f)\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 293, in load\n",
            "    return loads(fp.read(),\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 346, in loads\n",
            "    return _default_decoder.decode(s)\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 337, in decode\n",
            "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 355, in raw_decode\n",
            "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
            "json.decoder.JSONDecodeError: Expecting value: line 45 column 1 (char 1155)\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:54:21] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:54:30] \"POST / HTTP/1.1\" 200 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 27, in detect_json_array_to_new_message_array\n",
            "    jsonArray = json.load(f)\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 293, in load\n",
            "    return loads(fp.read(),\n",
            "  File \"/usr/lib/python3.9/json/__init__.py\", line 346, in loads\n",
            "    return _default_decoder.decode(s)\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 337, in decode\n",
            "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
            "  File \"/usr/lib/python3.9/json/decoder.py\", line 353, in raw_decode\n",
            "    obj, end = self.scan_once(s, idx)\n",
            "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 68 column 1 (char 1780)\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 07:54:55] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 26, in detect_json_array_to_new_message_array\n",
            "    with open(fileName,encoding='utf8') as f:\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/line_bot_content/我要找弱小外星人.json'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:00:45] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 26, in detect_json_array_to_new_message_array\n",
            "    with open(fileName,encoding='utf8') as f:\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/line_bot_content/我要找強壯外星人.json'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:00:46] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 26, in detect_json_array_to_new_message_array\n",
            "    with open(fileName,encoding='utf8') as f:\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/line_bot_content/我要找暴力外星人.json'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:00:47] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:02:32] \"POST / HTTP/1.1\" 200 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 26, in detect_json_array_to_new_message_array\n",
            "    with open(fileName,encoding='utf8') as f:\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/line_bot_content/我要找弱小外星人.json'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:02:47] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 26, in detect_json_array_to_new_message_array\n",
            "    with open(fileName,encoding='utf8') as f:\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/line_bot_content/我要找強壯外星人.json'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:02:48] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 26, in detect_json_array_to_new_message_array\n",
            "    with open(fileName,encoding='utf8') as f:\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/line_bot_content/我要找暴力外星人.json'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:02:49] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 18, in process_text_message\n",
            "    line_bot_api.reply_message(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 116, in reply_message\n",
            "    self._post(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2033, in _post\n",
            "    self.__check_error(response)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2069, in __check_error\n",
            "    raise LineBotApiError(\n",
            "linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=7b0f951f-3d5d-4c04-9d82-353bd2ec9bea, error_response={\"details\": [{\"message\": \"Invalid action URI\"}], \"message\": \"A message (messages[0])\\u00a0in the request body is invalid\"}, headers={'Content-Type': 'application/json', 'Server': 'envoy', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '7b0f951f-3d5d-4c04-9d82-353bd2ec9bea', 'x-xss-protection': '1; mode=block', 'Content-Length': '114', 'Expires': 'Thu, 16 Mar 2023 08:05:42 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 16 Mar 2023 08:05:42 GMT', 'Connection': 'close'}\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:05:42] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 18, in process_text_message\n",
            "    line_bot_api.reply_message(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 116, in reply_message\n",
            "    self._post(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2033, in _post\n",
            "    self.__check_error(response)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2069, in __check_error\n",
            "    raise LineBotApiError(\n",
            "linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=3b29ad01-8344-4fcd-9c60-31e21d8fbb19, error_response={\"details\": [{\"message\": \"Invalid action URI\"}], \"message\": \"A message (messages[0])\\u00a0in the request body is invalid\"}, headers={'Content-Type': 'application/json', 'Server': 'envoy', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '3b29ad01-8344-4fcd-9c60-31e21d8fbb19', 'x-xss-protection': '1; mode=block', 'Content-Length': '114', 'Expires': 'Thu, 16 Mar 2023 08:05:48 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 16 Mar 2023 08:05:48 GMT', 'Connection': 'close'}\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:05:48] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 18, in process_text_message\n",
            "    line_bot_api.reply_message(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 116, in reply_message\n",
            "    self._post(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2033, in _post\n",
            "    self.__check_error(response)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2069, in __check_error\n",
            "    raise LineBotApiError(\n",
            "linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=4d59a166-e481-45ee-a221-73b3b1ee05a4, error_response={\"details\": [{\"message\": \"Invalid action URI\"}], \"message\": \"A message (messages[0])\\u00a0in the request body is invalid\"}, headers={'Content-Type': 'application/json', 'Server': 'envoy', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '4d59a166-e481-45ee-a221-73b3b1ee05a4', 'x-xss-protection': '1; mode=block', 'Content-Length': '114', 'Expires': 'Thu, 16 Mar 2023 08:14:32 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 16 Mar 2023 08:14:32 GMT', 'Connection': 'close'}\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:14:32] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 39, in detect_json_array_to_new_message_array\n",
            "    message_type = jsonObject.get('type')\n",
            "AttributeError: 'str' object has no attribute 'get'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:14:54] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 39, in detect_json_array_to_new_message_array\n",
            "    message_type = jsonObject.get('type')\n",
            "AttributeError: 'str' object has no attribute 'get'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:14:57] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 18, in process_text_message\n",
            "    line_bot_api.reply_message(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 116, in reply_message\n",
            "    self._post(\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2033, in _post\n",
            "    self.__check_error(response)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/api.py\", line 2069, in __check_error\n",
            "    raise LineBotApiError(\n",
            "linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=8e90feaa-83b8-4d4e-ae7c-bf9ed305c970, error_response={\"details\": [{\"message\": \"Invalid action URI\"}], \"message\": \"A message (messages[0])\\u00a0in the request body is invalid\"}, headers={'Content-Type': 'application/json', 'Server': 'envoy', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '8e90feaa-83b8-4d4e-ae7c-bf9ed305c970', 'x-xss-protection': '1; mode=block', 'Content-Length': '114', 'Expires': 'Thu, 16 Mar 2023 08:15:15 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 16 Mar 2023 08:15:15 GMT', 'Connection': 'close'}\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:15:15] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 26, in detect_json_array_to_new_message_array\n",
            "    with open(fileName,encoding='utf8') as f:\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/line_bot_content/我要找強壯外星人.json'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:15:16] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n",
            "ERROR:__main__:Exception on / [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 2528, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1825, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 1799, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
            "  File \"<ipython-input-5-4651184fc34d>\", line 13, in callback\n",
            "    handler.handle(body, signature)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 263, in handle\n",
            "    self.__invoke_func(func, event, payload)\n",
            "  File \"/usr/local/lib/python3.9/dist-packages/linebot/webhook.py\", line 275, in __invoke_func\n",
            "    func(event)\n",
            "  File \"<ipython-input-11-15c096b7d6ad>\", line 15, in process_text_message\n",
            "    result_message_array = detect_json_array_to_new_message_array(replyJsonPath)\n",
            "  File \"<ipython-input-10-4f93eb169662>\", line 26, in detect_json_array_to_new_message_array\n",
            "    with open(fileName,encoding='utf8') as f:\n",
            "FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/line_bot_content/我要找暴力外星人.json'\n",
            "INFO:werkzeug:127.0.0.1 - - [16/Mar/2023 08:15:18] \"\u001b[35m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 500 -\n"
          ]
        }
      ],
      "source": [
        "# 主程序運行\n",
        "app.run()"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "name": "015_把line_bot_designer的消息變成json.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.8.6"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
